export interface Post{
    AREANM: string, 
    DIV:string,
    DTLCONT:string, 
    GUBUN: string,
    IMGURL: string,
    MAXCLASSNM: string,
    MINCLASSNM: string
    PAYATNM: string,
    PLACENM:string,
    RCPTBGNDT:string,
    RCPTENDDT:string,
    REVSTDDAY:Number,
    REVSTDDAYNM:string,
    SERVICE:string,
    SVCID:string,
    SVCNM:string,
    SVCOPNBGNDT:string,
    SVCOPNENDDT:string,
    SVCSTATNM:string,
    SVCURL: string,
    TELNO: string,
    USETGTINFO: string,
    V_MAX: string,
    V_MIN: string,
    X: string,
    Y: string,
};
