import Head from 'next/head'
import Link from "next/link"
import Image from "next/image"
import GallaryView from '@/components/GalleryView'
import Footer from '@/components/Footer'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>서울 플레이 리스트</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <nav className={styles.topnav}>
        <div className={styles.leftnav}>
          <a href="#main">MAIN</a>
          <a href="#recommend">추천플레이</a>
          <a href="#scrap">스크랩</a>
        </div>
        <div className={styles.rightnav}>
          <Link href="/search">
            <div className={styles.searchbar}>
              <div className={styles.searchbtn}></div>
            </div>
          </Link>
        </div>
      </nav>

      <div id="main" className={styles.main}>

        <div className={styles.maintitle}>
          서울<br/>플레이<br/>리스트
          <div className={styles.undertitle}>
          서울시 공공서비스예약(종합) 정보<br/>
          서울시 및 산하기관, 자치구의 체육시설, 시설대관, 교육, 문화행사, 진료 등의 상세 예약정보를 제공합니다.
        </div>
        </div>

        <div className={styles.mainimage}>
          <Image
            src="/images/seoulimg.jpg"
            alt="image of seoul"
            layout="fill"
            objectFit="cover"
            quality={100}
            ></Image>
        </div>
      </div>

      <div id="recommend">
        <GallaryView key={null} type={undefined} props={{title: "추천 플레이"}} />
      </div>
      <div id="scrap">
        <GallaryView key={null} type={undefined} props={{title: "스크랩"}} />
      </div>

      <Footer></Footer>
    </>
  )
}


      /*
      <main className={styles.main}>
        <h1>Hello Next!</h1>
        <Image
          src="/images/kimchi.jpg"
          height={200}
          width={300}
          alt="kimchi"
          />
        <Link href="/posts/first-post">
          first-post로 가기
        </Link>
        
      </main>
      */